### ISSUE TITLE
8x Larger satellite Image

### ISSUE THREAD

**Issue by Sven-vh** [S-Comic/Guessrpunk#5]
Hi,

First of all I want to say that I love playing GuessrPunk.
I'm not sure if you're still active on this project because last commit was 10 months ago.
Anyway, the only struggle I had while playing was that the satellite image is too blurry to pin point the exact location on the map. That's why I made this 16kx16k image of the Cyberpunk 2077 map.

Now this might be too large to load all at once so I also have the 4096 256x256 tiled images if that might be helpfull. So have the low res image at first and when the user zooms in they load the higher quality ones. I think this is possible with the `<TileLayer>` atributre of leaflet.

(Github is saying the file is too large so I can't share it but let me know if I you want to image to update it and we'll figure something out.)

**Comment by S-Comic** [comment]
Hi,

I'm glad to hear you're enjoying this little project!

I'm not actively developing it at the moment, though I'd be more than happy to update the Night City map if you've already made the assets for it and you're willing to share them. My usage of leaflet so-far has been very surface level but from what I can see `<TileLayer>` would be the way to go.

If you'd like to upload the files to a google drive (or similar) I'd be happy to download them and give it a shot - I really appreciate the offer! This might just be the motivation I need to jump back into the game and add some locations from the DLC 😄

**Comment by Sven-vh** [comment]
Awesome to hear!
I looked through the code to see if I could add it myself and maybe merge it but I'm a game dev in C++ and C# and never worked with either Next or Leaflet. The only thing I got "working" was changing the satellite image to the 16k image. But even then it was way too laggy and the markers were on the wrong positions.

Sadly I have no way of getting the images from the new update with the Phantom Liberty DLC. 
It would've been cool if there was an option to enable or disable DLC locations (since not everyone has purchased the DLC) but if I ever get my hands on those images I'm sure to let you know!

About the images. Here is the download link for the tiles and the full image: [Drive](https://drive.google.com/file/d/1XORHYeG4qzZhCOFLCyrspMISov93Z3FH/view?usp=sharing)
The full image is 16384x16384. There are some transparent borders around the map (this is also the reason there are some black/transparent tiles in the folder)

I've renamed the images so that you can easily read them. It is a 64*64 grid so there are 4096 images total, each being 256x256 in resolution (around 415MB total). The images are named like this: `{x}-{y}.png`. 

The files I gave you are for the 16kx16k satellite image. I also have 32k and 64k but I feel like these images would take up too much space for a web game. (Loading the 64k image breaks my PC) I also have the 2k, 4k and 8k images if you need those for something but I found that 16k looks the best without pushing the limit too much.

Let me know if I can be of further assistance!
Good luck!

**Comment by S-Comic** [comment]
Thanks for sending those images over!

I've had a go at implementing them with TileLayer and it's ultimately been successful, though as you noted when using the 16k image the markers are now in the wrong positions. I don't _think_ there's an easy way to fix this because the images are different shapes and the 16k one covers a larger area of the map than the other, so if it's not possible to fix mathematically I may just have to re-enter the locations manually.

When I find some time over the next few days I'll have a proper look into fixing the coordinates and push up a functional branch to test with. Thanks again!

**Comment by S-Comic** [comment]
I've finally had the time to implement this and it's worked quite well! I've had to downscale the image from 16k to around 13k so that its not using too much bandwidth or storage, but it's still a very noticeable improvement over the old map.

![image](https://github.com/S-Comic/Guessrpunk/assets/32823294/aa853541-a469-43b9-9375-0ae883e52c04)

There were some changes that had to be made to how coordinates are handled as part of this so there's been some minor knock-on effects but nothing drastic.  The new version can be tested [here](https://cyber-guessr-git-feature-sjimplement-16k-map-s-comic.vercel.app). I'll leave it for a little while and do some testing to make sure it's not using too much bandwidth, and then merge tomorrow if all is well.

Thanks again!
